# Generated by Django 5.0.2 on 2024-02-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0002_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="author",
            field=models.CharField(max_length=128),
        ),
    ]
